version: "3.9"
services:
  client:
    container_name: iac-client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AWSCLI_VERSION: "2.13.9"
        TERRAFORM_VERSION: "1.5.5"
        TERRAGRUNT_VERSION: "0.50.2"
    tty: true
    volumes:
      - ./:/app
    env_file:
      - .env/aws.env
